# .github/workflows/debug-pr.yml
name: Debug PR Trigger

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - "prod/**"

jobs:
  debug:
    name: Debug PR Event
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub context
        run: |
          echo "head_ref: ${{ github.head_ref }}"
          echo "base_ref: ${{ github.base_ref }}"
          echo "ref: ${{ github.ref }}"
