name: test
on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - 'prod/**'
      
jobs:
  check_pr_source:
    runs-on: ubuntu-latest
    steps:
      - name: Check source branch
        run: |
          SOURCE_BRANCH="${{ github.head_ref }}"
          if [[ ! "$SOURCE_BRANCH" =~ ^uat/ ]]; then
            echo "Error: Pull requests into a 'prod/*' branch must originate from a 'uat/*' branch."
            exit 1
          fi
