# .github/workflows/test-any-pr.yml
name: Test Any PR 1

on: pull_request

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 Hello from GitHub Actions on PR to ${{ github.base_ref }}"
